using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace WudFilmApp.Models
{
  /// <summary>
  /// The Showtime class represents information about a specific showtime for 1 movie.
  /// </summary>
  /// <remarks>
  /// Showtimes are uniquely identifiable by their Id property. Showtimes exhibit a many-to-one relationship with Movies. Information about the related movie can be access via the MovieId and Movie properties.  A showtime cannot exist without a corresponding movie. 
  /// </remarks>
  public class Showtime
  {
    /// <summary>
    /// This is the key field for showtimes. This field is automatically generated by the database, cannot be changed, cannot be null, and will be a number greater than 0. It uniquely Identifies a Movie showtimes within the WUD Film App Database.  
    /// </summary>
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// This is a foreign key reference to the Movie that this Showtime is for. It provides the pathway for linking the Movie navigation property. This is a non-null positive integer value which must match the Id of at least 1 existing Id in the Movies table.
    /// </summary>
    [ForeignKey(nameof(Movie))]
    public int MovieId { get; set; }

    /// <summary>
    /// This is a navigation property referencing the movie that the showtime is for. 
    /// </summary>
    public virtual Movie Movie { get; set; }

    /// <summary>
    /// This is a non-null DateTime indicating the date and time that the Movie will be shown.
    /// </summary>
    [Required]
    public DateTime ShowDateTime { get; set; }

    /// <summary>
    /// This is a non-null, calculated property which indicates if the <see cref="ShowDateTime"/> of this showtime has already passed (The DateTime listed has already occured) 
    /// </summary>
    [NotMapped]
    [DisplayName("Has Showtime Passed")]
    public bool HasShowtimePassed => ShowDateTime < DateTime.Now;

    /// <summary>
    /// This is an internal property to indicate if the showing has been booked.
    /// </summary>
    [Required]
    public bool BookingConfirmed { get; set; }

    /// <summary>
    /// This is an internal property to indicate if there is a publicity form.
    /// </summary>
    [Required]
    public bool PublicityFormSent { get; set; }

    /// <summary>
    /// This is an internal property to indicate if the event is a WUD event
    /// </summary>
    [Required]
    public bool WUDFilm { get; set; }

    /// <summary>
    /// This is an internal property to indicate whether a Facebook announcement has been made.
    /// </summary>
    public bool FBEventMade { get; set; }

    /// <summary>
    /// This is the name of the WUD Film member taking the lead of the event.
    /// </summary>
    public String PointPerson { get; set; }

    /// <summary>
    /// This is the name of the WUD Film member working the projector.
    /// </summary>
    public String Projectionist { get; set; }

    /// <summary>
    /// This is the name of the Film Distributor.
    /// </summary>
    public String Distributor { get; set; }

    /// <summary>
    /// Media format for this movie
    /// </summary>
    public string Format { get; set; }

    /// <summary>
    /// List of close-captioning and auditory assistance available for this film
    /// </summary>
    //public ICollection<String> CCAP { get; set; }

    /// <summary>
    /// This is an internal property to indicate if a Blu-ray has been ordered for the showing.
    /// </summary>
    public bool MediaOrdered { get; set; }

    /// <summary>
    /// This is an internal property to indicate if the media has arrived.
    /// </summary>
    public DateTime MediaArrived { get; set; }

    /// <summary>
    /// This is an internal property to indicate if the media has been returned.
    /// </summary>
    public DateTime MediaReturned { get; set; }

    /// <summary>
    /// This is an internal property for the tracking number of the returned item.
    /// </summary>
    public String MediaReturnTrackingNumber { get; set; }

    /// <summary>
    /// This is an internal property for the event collaborator organization if there is one.
    /// </summary>
    public String Collaborator { get; set; }

    /// <summary>
    /// This is an internal property for the point of contact with the collaborator.
    /// </summary>
    public String CollaboratorPerson { get; set; }

    /// <summary>
    /// This is an internal property for the collabortato contact's contact information.
    /// </summary>
    public String CollaboratorContactInfo { get; set; }

    /// <summary>
    /// This is the property to record a showing's attendence.
    /// </summary>
    public int ShowingAttendence { get; set; }

    /// <summary>
    /// This is an additional field for additional notes for the showing.
    /// </summary>
    public String Notes { get; set; }
  }
}